[package]
name = "edgelet-utils"
version = "0.1.0"
authors = ["Azure IoT Edge Devs"]
publish = false

[dependencies]
failure = {path = "../../../failure"}
futures = "0.1"
log = "0.4"
serde = "1.0"
serde_json = {path = "../../../json"}

[dev_dependencies]
serde_derive = "1.0"
