[package]
name = "systemd"
version = "0.1.0"
authors = ["Azure IoT Edge Devs"]

[dependencies]
failure = {path = "../../../failure"}
failure_derive = "0.1"
log = "0.4"
nix = {path = "../../../nix"}

[dev-dependencies]
lazy_static = "1.0"
